import './globals.css'
import { Header } from './components/Header'
import { Sidebar } from './components/Sidebar'
import { AuthContextProvider } from '@components/context/AuthContext'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body>
            <AuthContextProvider>
              <Header />
              <div className="flex">
                    <Sidebar />
                    {children}
              </div>
            </AuthContextProvider>
          </body>
      </html>
  )
}
