"use client"

import './globals.css'
import { Header } from './components/Header'
import { AuthContextProvider } from '@components/context/AuthContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <AuthContextProvider>
          <body>
              <Header />
              {children}
          </body>
      </AuthContextProvider>
    </html>
  )
}
