import './globals.css'
import { Header } from './components/Header'
import { Sidebar } from './components/Sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
